## 환경보호 데이터 확인

In [1]:
import pandas as pd

In [16]:
greens = pd.read_csv('../data/raw/인구1인당_도시지역_면적_20250812103523.csv', encoding='cp949')

In [17]:
greens.head()

,소재지(시군구)별(1),소재지(시군구)별(2),2021,2021.1,2021.2,2021.3,2021.4,2021.5,2021.6,2022,...,2022.4,2022.5,2022.6,2023,2023.1,2023.2,2023.3,2023.4,2023.5,2023.6
0,소재지(시군구)별(1),소재지(시군구)별(2),도시지역 인구 (명),도시지역 면적 (㎡),1인당면적 주+상+공 (㎡),주거지역 (㎡),상업지역 (㎡),공업지역 (㎡),1인당면적 녹지지역 (㎡),도시지역 인구 (명),...,상업지역 (㎡),공업지역 (㎡),1인당면적 녹지지역 (㎡),도시지역 인구 (명),도시지역 면적 (㎡),1인당면적 주+상+공 (㎡),주거지역 (㎡),상업지역 (㎡),공업지역 (㎡),1인당면적 녹지지역 (㎡)
1,인천광역시,소계,2881117,529699653,73.78,42.06,8.24,23.48,101.93,2899766,...,8.44,22.68,101.44,2930599,512816173,74.17,42.45,8.53,23.19,99.45
2,인천광역시,중구,143633,141263611,219.73,85.9,41.65,92.18,763.24,152931,...,39.12,86.58,716.84,158958,141699879,200.44,77.34,39.63,83.48,689.99
3,인천광역시,동구,61486,7595909,109.99,39.09,7.42,63.48,13.52,58999,...,7.73,66.16,14.07,59482,7564543,111.96,40.43,7.69,63.85,15.21
4,인천광역시,미추홀구,407464,24840389,50.12,35.83,7.9,6.39,10.84,406004,...,7.92,6.41,10.88,405995,24921836,50.46,36.74,8.04,5.68,10.92

In [19]:
greens.loc[greens['2022.5'] == '-', :]

,소재지(시군구)별(1),소재지(시군구)별(2),2021,2021.1,2021.2,2021.3,2021.4,2021.5,2021.6,2022,...,2022.4,2022.5,2022.6,2023,2023.1,2023.2,2023.3,2023.4,2023.5,2023.6
11,인천광역시,옹진군,0,7585977,0,0,0,0,0,-,...,-,-,-,0,7598931,0,0,0,0,0

In [20]:
greens = pd.read_csv('../data/raw/녹지및도시지역면젹_녹지지역면적비율.csv')

In [21]:
greens.head()

,SGG_NAME,URBAN_AREA_20,GREEN_AREA_20,GREEN_RT_20,URBAN_AREA_21,GREEN_AREA_21,GREEN_RT_21,URBAN_AREA_22,GREEN_AREA_22,GREEN_RT_22,URBAN_AREA_23,GREEN_AREA_23,GREEN_RT_23
0,강원특별자치도 강릉시,84958649,53746927,63.26,84958649,53746927,63.26,84958649,53746927,63.26,78392991,53746927,68.56
1,강원특별자치도 고성군,12421767,8304854,66.86,12421767,8304854,66.86,12421947,8304854,66.86,11979402,8304854,69.33
2,강원특별자치도 동해시,124014784,81863718,66.01,124014784,81863718,66.01,124014784,81770077,65.94,106174140,81745526,76.99
3,강원특별자치도 삼척시,79882143,56229816,70.39,79882140,56229797,70.39,79883698,56226482,70.39,79101671,56056231,70.87
4,강원특별자치도 속초시,42065437,27311021,64.93,42065437,27311981,64.93,42065436,27373662,65.07,42065436,27373662,65.07

In [22]:
greens.columns

Index(['SGG_NAME', 'URBAN_AREA_20', 'GREEN_AREA_20', 'GREEN_RT_20',
       'URBAN_AREA_21', 'GREEN_AREA_21', 'GREEN_RT_21', 'URBAN_AREA_22',
       'GREEN_AREA_22', 'GREEN_RT_22', 'URBAN_AREA_23', 'GREEN_AREA_23',
       'GREEN_RT_23'],
      dtype='object')

In [23]:
for col in greens.columns:
    print(greens.loc[greens[col] == '-', :])

Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []
Empty DataFrame
Columns: [SGG_NAME, URBAN_AREA_20, GREEN_AREA_20, GREEN_RT_20, URBAN_AREA_21, GREEN_AREA_21, GREEN_RT_21, URBAN_AREA_22, GREEN_AREA_22, GREEN_RT_22, URBAN_AREA_23, GREEN_AREA_23, GREEN_RT_23]
Index: []

In [27]:
for col in greens.columns:
    print(f"{col}: {len(greens.loc[greens[col] == '-', :])}")

SGG_NAME: 0
URBAN_AREA_20: 0
GREEN_AREA_20: 0
GREEN_RT_20: 0
URBAN_AREA_21: 0
GREEN_AREA_21: 0
GREEN_RT_21: 0
URBAN_AREA_22: 0
GREEN_AREA_22: 0
GREEN_RT_22: 0
URBAN_AREA_23: 0
GREEN_AREA_23: 0
GREEN_RT_23: 0

In [28]:
greens.isnull().sum()

SGG_NAME         0
URBAN_AREA_20    0
GREEN_AREA_20    0
GREEN_RT_20      0
URBAN_AREA_21    0
GREEN_AREA_21    0
GREEN_RT_21      0
URBAN_AREA_22    0
GREEN_AREA_22    0
GREEN_RT_22      0
URBAN_AREA_23    0
GREEN_AREA_23    0
GREEN_RT_23      0
dtype: int64

## 보건 데이터 확인

In [35]:
import glob
import os

health_dir = '../data/보건/'

for hos in glob.glob('../data/보건/*'):
    tmp = pd.read_csv(hos)
    print(os.path.basename(hos), ':')
    
    print('- 의 개수:')

    for col in tmp.columns:
        print(f"{col}: {len(tmp.loc[tmp[col] == '-', :])}")
    
    print('결측치 개수: ')
    print(tmp.isnull().sum())
    print(list(tmp.loc[tmp.isnull().any(axis=1),'SGG_NAME']))
    print('='*50)

병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
HOSPITAL_COUNT_20: 0
HOSPITAL_COUNT_21: 0
HOSPITAL_COUNT_22: 0
HOSPITAL_COUNT_23: 0
결측치 개수:
SGG_NAME             0
HOSPITAL_COUNT_20    0
HOSPITAL_COUNT_21    0
HOSPITAL_COUNT_22    0
HOSPITAL_COUNT_23    0
dtype: int64
[]
==================================================
보건복지시설수_전국.csv :
- 의 개수:
SGG_NAME: 0
WELFARE_FACILITY_20: 0
WELFARE_FACILITY_21: 0
WELFARE_FACILITY_22: 0
WELFARE_FACILITY_23: 0
결측치 개수:
SGG_NAME               0
WELFARE_FACILITY_20    2
WELFARE_FACILITY_21    1
WELFARE_FACILITY_22    1
WELFARE_FACILITY_23    1
dtype: int64
['인천광역시 강화군', '인천광역시 옹진군']
==================================================
보건소수_전국.csv :
- 의 개수:
SGG_NAME: 0
PHC_CNT_20: 0
PHC_CNT_21: 0
PHC_CNT_22: 0
PHC_CNT_23: 0
결측치 개수:
SGG_NAME      0
PHC_CNT_20    0
PHC_CNT_21    0
PHC_CNT_22    0
PHC_CNT_23    0
dtype: int64
[]
==================================================
상급종합병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
ADV_HOSP_20: 0
ADV_HOSP_21: 0
ADV_HOSP_22: 0
ADV_HOSP_23: 0
결측치 개수:
SGG_NAME       0
ADV_HOSP_20    0
ADV_HOSP_21    0
ADV_HOSP_22    0
ADV_HOSP_23    0
dtype: int64
[]
==================================================
약국수_전국.csv :
- 의 개수:
SGG_NAME: 0
PHARMACY_20: 0
PHARMACY_21: 0
PHARMACY_22: 0
PHARMACY_23: 0
결측치 개수:
SGG_NAME       0
PHARMACY_20    0
PHARMACY_21    0
PHARMACY_22    0
PHARMACY_23    0
dtype: int64
[]
==================================================
요양병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
NURS_HOSP_20: 0
NURS_HOSP_21: 0
NURS_HOSP_22: 0
NURS_HOSP_23: 0
결측치 개수:
SGG_NAME        0
NURS_HOSP_20    0
NURS_HOSP_21    0
NURS_HOSP_22    0
NURS_HOSP_23    0
dtype: int64
[]
==================================================
의사수_치과의사수_한의사수_전국.csv :
- 의 개수:
SGG_NAME: 0
DOCTORS_20: 0
DENTISTS_20: 0
ORIENTAL_DOCS_20: 0
DOCTORS_21: 0
DENTISTS_21: 0
ORIENTAL_DOCS_21: 0
DOCTORS_22: 0
DENTISTS_22: 0
ORIENTAL_DOCS_22: 0
DOCTORS_23: 0
DENTISTS_23: 0
ORIENTAL_DOCS_23: 0
결측치 개수:
SGG_NAME            0
DOCTORS_20          0
DENTISTS_20         0
ORIENTAL_DOCS_20    0
DOCTORS_21          0
DENTISTS_21         0
ORIENTAL_DOCS_21    0
DOCTORS_22          0
DENTISTS_22         0
ORIENTAL_DOCS_22    0
DOCTORS_23          0
DENTISTS_23         0
ORIENTAL_DOCS_23    0
dtype: int64
[]
==================================================
의원수_전국.csv :
- 의 개수:
SGG_NAME: 0
CLINIC_20: 0
CLINIC_21: 0
CLINIC_22: 0
CLINIC_23: 0
결측치 개수:
SGG_NAME     0
CLINIC_20    0
CLINIC_21    0
CLINIC_22    0
CLINIC_23    0
dtype: int64
[]
==================================================
종합병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
GEN_HOSP_20: 0
GEN_HOSP_21: 0
GEN_HOSP_22: 0
GEN_HOSP_23: 0
결측치 개수:
SGG_NAME       0
GEN_HOSP_20    0
GEN_HOSP_21    0
GEN_HOSP_22    0
GEN_HOSP_23    0
dtype: int64
[]
==================================================
천명당의료기관병상수_전국.csv :
- 의 개수:
SGG_NAME: 0
BED_PER_1000_20: 0
BED_PER_1000_21: 0
BED_PER_1000_22: 0
BED_PER_1000_23: 0
결측치 개수:
SGG_NAME           0
BED_PER_1000_20    1
BED_PER_1000_21    1
BED_PER_1000_22    1
BED_PER_1000_23    1
dtype: int64
['경기도 과천시']
==================================================
총병상수_전국.csv :
- 의 개수:
SGG_NAME: 0
BED_TOTAL_20: 0
BED_TOTAL_21: 0
BED_TOTAL_22: 0
BED_TOTAL_23: 0
결측치 개수:
SGG_NAME        0
BED_TOTAL_20    1
BED_TOTAL_21    1
BED_TOTAL_22    1
BED_TOTAL_23    1
dtype: int64
['경기도 과천시']
==================================================
치과병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
DENTAL_HOSP_20: 0
DENTAL_HOSP_21: 0
DENTAL_HOSP_22: 0
DENTAL_HOSP_23: 0
결측치 개수:
SGG_NAME          0
DENTAL_HOSP_20    0
DENTAL_HOSP_21    0
DENTAL_HOSP_22    0
DENTAL_HOSP_23    0
dtype: int64
[]
==================================================
한방병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
ORIENTAL_HOSP_20: 0
ORIENTAL_HOSP_21: 0
ORIENTAL_HOSP_22: 0
ORIENTAL_HOSP_23: 0
결측치 개수:
SGG_NAME            0
ORIENTAL_HOSP_20    0
ORIENTAL_HOSP_21    0
ORIENTAL_HOSP_22    0
ORIENTAL_HOSP_23    0
dtype: int64
[]
==================================================

In [41]:
welf = pd.read_csv(health_dir + '보건복지시설수_전국.csv')

In [45]:
welf.loc[welf.isnull().any(axis=1),:]

,SGG_NAME,WELFARE_FACILITY_20,WELFARE_FACILITY_21,WELFARE_FACILITY_22,WELFARE_FACILITY_23
219,인천광역시 강화군,NaN,1.0,1.0,1.0
227,인천광역시 옹진군,NaN,NaN,NaN,NaN

In [48]:
welf2 = welf.copy()
welf2 = welf2.fillna(0)

In [49]:
welf2.loc[welf.isnull().any(axis=1),:]

,SGG_NAME,WELFARE_FACILITY_20,WELFARE_FACILITY_21,WELFARE_FACILITY_22,WELFARE_FACILITY_23
219,인천광역시 강화군,0.0,1.0,1.0,1.0
227,인천광역시 옹진군,0.0,0.0,0.0,0.0

In [50]:
print(welf2.isnull().sum())

SGG_NAME               0
WELFARE_FACILITY_20    0
WELFARE_FACILITY_21    0
WELFARE_FACILITY_22    0
WELFARE_FACILITY_23    0
dtype: int64

In [70]:
for col in welf2.columns:
    print(col, len(welf2.loc[welf2[col] == '-', :]))

SGG_NAME 0
WELFARE_FACILITY_20 0
WELFARE_FACILITY_21 0
WELFARE_FACILITY_22 0
WELFARE_FACILITY_23 0

In [51]:
per1000 = pd.read_csv(health_dir + '천명당의료기관병상수_전국.csv')
per1000.head()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
0,강원특별자치도 강릉시,12.5,12.4,11.8,11.3
1,강원특별자치도 고성군,0.0,0.0,0.0,0.0
2,강원특별자치도 동해시,15.9,14.5,14.6,14.3
3,강원특별자치도 삼척시,6.2,6.5,6.5,6.7
4,강원특별자치도 속초시,10.5,10.3,10.2,10.1

In [52]:
per1000.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    1
BED_PER_1000_21    1
BED_PER_1000_22    1
BED_PER_1000_23    1
dtype: int64

In [54]:
per1000.loc[per1000.isnull().any(axis=1),:]
per1000_zero = per1000.fillna(0)

In [55]:
per1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [58]:
for col in per1000_zero.columns:
    print(col, len(per1000_zero.loc[per1000_zero[col] == '-',:]))

SGG_NAME 0
BED_PER_1000_20 0
BED_PER_1000_21 0
BED_PER_1000_22 0
BED_PER_1000_23 0

In [61]:
totbed = pd.read_csv(health_dir + '총병상수_전국.csv')
totbed.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    1
BED_TOTAL_21    1
BED_TOTAL_22    1
BED_TOTAL_23    1
dtype: int64

In [64]:
totbed.loc[totbed.isnull().any(axis=1),:]
## 0으로 채우기
totbed_zero = totbed.fillna(0)

In [66]:
totbed_zero.loc[totbed.isnull().any(axis=1),:]

    SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
165  경기도 과천시           0.0           0.0           0.0           0.0

In [67]:
totbed_zero.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64

In [68]:
for col in totbed_zero.columns:
    print(col, len(totbed_zero.loc[totbed_zero[col] == '-',:]))

SGG_NAME 0
BED_TOTAL_20 0
BED_TOTAL_21 0
BED_TOTAL_22 0
BED_TOTAL_23 0

In [71]:
## to_csv
welf2.to_csv('보건복지시설수.csv', index=False)
per1000_zero.to_csv('천명당의료기관병상수.csv', index=False)
totbed_zero.to_csv('총병상수.csv', index=False)

In [74]:
import glob
import os

health_dir = '../data/processed/'

for hos in glob.glob('../data/processed/*'):
    tmp = pd.read_csv(hos)
    print(os.path.basename(hos), ':')
    
    print('- 의 개수:')

    for col in tmp.columns:
        print(f"{col}: {len(tmp.loc[tmp[col] == '-', :])}")
    
    print('결측치 개수: ')
    print(tmp.isnull().sum())
    print(list(tmp.loc[tmp.isnull().any(axis=1),'SGG_NAME']))
    print('='*50)

병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
HOSPITAL_COUNT_20: 0
HOSPITAL_COUNT_21: 0
HOSPITAL_COUNT_22: 0
HOSPITAL_COUNT_23: 0
결측치 개수:
SGG_NAME             0
HOSPITAL_COUNT_20    0
HOSPITAL_COUNT_21    0
HOSPITAL_COUNT_22    0
HOSPITAL_COUNT_23    0
dtype: int64
[]
==================================================
보건복지시설수.csv :
- 의 개수:
SGG_NAME: 0
WELFARE_FACILITY_20: 0
WELFARE_FACILITY_21: 0
WELFARE_FACILITY_22: 0
WELFARE_FACILITY_23: 0
결측치 개수:
SGG_NAME               0
WELFARE_FACILITY_20    0
WELFARE_FACILITY_21    0
WELFARE_FACILITY_22    0
WELFARE_FACILITY_23    0
dtype: int64
[]
==================================================
보건소수_전국.csv :
- 의 개수:
SGG_NAME: 0
PHC_CNT_20: 0
PHC_CNT_21: 0
PHC_CNT_22: 0
PHC_CNT_23: 0
결측치 개수:
SGG_NAME      0
PHC_CNT_20    0
PHC_CNT_21    0
PHC_CNT_22    0
PHC_CNT_23    0
dtype: int64
[]
==================================================
상급종합병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
ADV_HOSP_20: 0
ADV_HOSP_21: 0
ADV_HOSP_22: 0
ADV_HOSP_23: 0
결측치 개수:
SGG_NAME       0
ADV_HOSP_20    0
ADV_HOSP_21    0
ADV_HOSP_22    0
ADV_HOSP_23    0
dtype: int64
[]
==================================================
약국수_전국.csv :
- 의 개수:
SGG_NAME: 0
PHARMACY_20: 0
PHARMACY_21: 0
PHARMACY_22: 0
PHARMACY_23: 0
결측치 개수:
SGG_NAME       0
PHARMACY_20    0
PHARMACY_21    0
PHARMACY_22    0
PHARMACY_23    0
dtype: int64
[]
==================================================
요양병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
NURS_HOSP_20: 0
NURS_HOSP_21: 0
NURS_HOSP_22: 0
NURS_HOSP_23: 0
결측치 개수:
SGG_NAME        0
NURS_HOSP_20    0
NURS_HOSP_21    0
NURS_HOSP_22    0
NURS_HOSP_23    0
dtype: int64
[]
==================================================
의사수_치과의사수_한의사수_전국.csv :
- 의 개수:
SGG_NAME: 0
DOCTORS_20: 0
DENTISTS_20: 0
ORIENTAL_DOCS_20: 0
DOCTORS_21: 0
DENTISTS_21: 0
ORIENTAL_DOCS_21: 0
DOCTORS_22: 0
DENTISTS_22: 0
ORIENTAL_DOCS_22: 0
DOCTORS_23: 0
DENTISTS_23: 0
ORIENTAL_DOCS_23: 0
결측치 개수:
SGG_NAME            0
DOCTORS_20          0
DENTISTS_20         0
ORIENTAL_DOCS_20    0
DOCTORS_21          0
DENTISTS_21         0
ORIENTAL_DOCS_21    0
DOCTORS_22          0
DENTISTS_22         0
ORIENTAL_DOCS_22    0
DOCTORS_23          0
DENTISTS_23         0
ORIENTAL_DOCS_23    0
dtype: int64
[]
==================================================
의원수_전국.csv :
- 의 개수:
SGG_NAME: 0
CLINIC_20: 0
CLINIC_21: 0
CLINIC_22: 0
CLINIC_23: 0
결측치 개수:
SGG_NAME     0
CLINIC_20    0
CLINIC_21    0
CLINIC_22    0
CLINIC_23    0
dtype: int64
[]
==================================================
종합병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
GEN_HOSP_20: 0
GEN_HOSP_21: 0
GEN_HOSP_22: 0
GEN_HOSP_23: 0
결측치 개수:
SGG_NAME       0
GEN_HOSP_20    0
GEN_HOSP_21    0
GEN_HOSP_22    0
GEN_HOSP_23    0
dtype: int64
[]
==================================================
천명당의료기관병상수.csv :
- 의 개수:
SGG_NAME: 0
BED_PER_1000_20: 0
BED_PER_1000_21: 0
BED_PER_1000_22: 0
BED_PER_1000_23: 0
결측치 개수:
SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64
[]
==================================================
총병상수.csv :
- 의 개수:
SGG_NAME: 0
BED_TOTAL_20: 0
BED_TOTAL_21: 0
BED_TOTAL_22: 0
BED_TOTAL_23: 0
결측치 개수:
SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64
[]
==================================================
치과병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
DENTAL_HOSP_20: 0
DENTAL_HOSP_21: 0
DENTAL_HOSP_22: 0
DENTAL_HOSP_23: 0
결측치 개수:
SGG_NAME          0
DENTAL_HOSP_20    0
DENTAL_HOSP_21    0
DENTAL_HOSP_22    0
DENTAL_HOSP_23    0
dtype: int64
[]
==================================================
한방병원수_전국.csv :
- 의 개수:
SGG_NAME: 0
ORIENTAL_HOSP_20: 0
ORIENTAL_HOSP_21: 0
ORIENTAL_HOSP_22: 0
ORIENTAL_HOSP_23: 0
결측치 개수:
SGG_NAME            0
ORIENTAL_HOSP_20    0
ORIENTAL_HOSP_21    0
ORIENTAL_HOSP_22    0
ORIENTAL_HOSP_23    0
dtype: int64
[]
==================================================