## 기후데이터 기초전처리
* 같은 시군구 내 관측소 값을 각 해마다 평균내어 하나로 처리

In [2]:
import pandas as pd

In [4]:
climate_sudo = pd.read_csv('../data/raw/기후데이터_수도권0811.csv', encoding='cp949')

In [8]:
climate_sudo.head(10)

,시군구별(1),시군구별(2),AVG_TEMP_20,AVG_MAX_TEMP_20,MAX_TEMP_20,AVG_MIN_TEMP_20,MIN_TEMP_20,AVG_WIND_SPD_20,MAX_GUST_SPD_20,MAX_GUST_DIR_DEG_20,...,TOTAL_RAIN_22,AVG_TEMP_23,AVG_MAX_TEMP_23,MAX_TEMP_23,AVG_MIN_TEMP_23,MIN_TEMP_23,AVG_WIND_SPD_23,MAX_GUST_SPD_23,MAX_GUST_DIR_DEG_23,TOTAL_RAIN_23
0,경기도,가평군,11.0,18.7,37.1,4.6,-20.1,1.1,23.6,225.0,...,1893.5,11.5,18.8,36.3,5.4,-22.4,0.9,15.3,316.0,1540.0
1,경기도,가평군,10.9,17.1,34.6,5.3,-17.9,1.2,22.6,117.0,...,1882.0,11.7,18.0,34.6,6.1,-21.3,1.1,18.7,270.5,1699.5
2,경기도,가평군,11.6,18.0,34.6,6.3,-15.4,1.3,20.5,194.1,...,1760.5,12.1,18.3,35.3,6.9,-19.2,1.3,17.3,42.2,1704.0
3,경기도,고양시,NaN,NaN,37.8,NaN,-14.9,NaN,15.0,354.4,...,1584.0,NaN,NaN,33.9,NaN,-19.4,NaN,16.1,331.9,510.0
4,경기도,고양시,11.9,17.5,34.7,6.9,-14.8,1.2,18.0,132.2,...,1668.5,12.3,17.8,33.8,7.4,-18.9,1.1,13.7,201.2,1274.0
5,경기도,과천시,12.8,18.4,34.7,7.7,-12.5,1.5,18.3,208.3,...,1391.5,13.2,19.2,35.6,7.9,-17.1,1.2,16.1,315.2,1407.5
6,경기도,과천시,9.3,13.2,30.7,6.2,-17.8,3.2,30.8,340.3,...,2053.0,10.8,14.9,32.5,7.5,-22.2,NaN,27.4,337.5,1772.5
7,경기도,과천시,13.1,18.2,36.0,8.7,-13.0,1.9,19.2,124.1,...,1496.5,NaN,NaN,35.6,NaN,-17.1,NaN,16.8,327.1,1255.5
8,경기도,광명시,14.0,18.1,35.6,10.4,-11.7,1.7,18.3,180.5,...,1820.5,14.7,19.1,37.5,11.0,-16.0,1.4,15.5,315.8,1548.0
9,경기도,광명시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1016.5,13.2,18.3,35.9,8.8,-17.8,1.6,15.8,259.6,1260.5

In [10]:
climate_sudo_mean = climate_sudo.groupby(['시군구별(1)','시군구별(2)']).mean().round(1)

In [14]:
print(climate_sudo_mean.shape)

(59, 36)

In [15]:
climate_sudo_mean.tail()

                 AVG_TEMP_20  AVG_MAX_TEMP_20  MAX_TEMP_20  AVG_MIN_TEMP_20  \
시군구별(1) 시군구별(2)
인천광역시   부평구             12.3             17.8         35.7              7.6
        서구              12.4             17.6         34.7              7.8
        연수구             13.0             17.2         35.7              9.4
        옹진군             12.3             15.5         32.1              9.5
        중구              12.2             16.4         33.6              8.5

                 MIN_TEMP_20  AVG_WIND_SPD_20  MAX_GUST_SPD_20  \
시군구별(1) 시군구별(2)
인천광역시   부평구            -13.7              1.2             16.7
        서구             -14.2              1.4             12.8
        연수구            -11.1              2.4             18.4
        옹진군            -10.4              3.1             25.4
        중구             -12.0              2.4             20.4

                 MAX_GUST_DIR_DEG_20  TOTAL_RAIN_20  AVG_TEMP_21  ...  \
시군구별(1) 시군구별(2)                                                   ...
인천광역시   부평구                    314.2         1437.0         12.8  ...
        서구                     260.2         1344.0         12.8  ...
        연수구                    279.4         1168.5         13.2  ...
        옹진군                    153.5         1114.5         12.7  ...
        중구                     207.5         1130.0         12.4  ...

                 TOTAL_RAIN_22  AVG_TEMP_23  AVG_MAX_TEMP_23  MAX_TEMP_23  \
시군구별(1) 시군구별(2)
인천광역시   부평구             1460.0         13.1             18.8         36.9
        서구              1552.0         12.7             18.2         35.2
        연수구             1395.0         13.5             18.0         36.2
        옹진군             1134.0         13.0             16.4         32.9
        중구              1330.2         12.7             16.9         34.4

                 AVG_MIN_TEMP_23  MIN_TEMP_23  AVG_WIND_SPD_23  \
시군구별(1) 시군구별(2)
인천광역시   부평구                  8.1        -16.2              1.2
        서구                   7.6        -17.8              1.6
        연수구                  9.6        -15.9              2.2
        옹진군                 10.0        -12.8              3.1
        중구                   9.3        -16.1              1.8

                 MAX_GUST_SPD_23  MAX_GUST_DIR_DEG_23  TOTAL_RAIN_23
시군구별(1) 시군구별(2)
인천광역시   부평구                 15.0                235.4         1438.5
        서구                  14.8                208.6         1279.8
        연수구                 19.4                260.2         1403.5
        옹진군                 24.7                227.7          938.2
        중구                  20.2                256.9         1230.5

[5 rows x 36 columns]

In [17]:
climate_sudo_mean.to_csv('../data/climate(기후데이터)/기후데이터_컬럼명변경_수도권.csv', encoding='utf-8')