### 데이터 결측치 처리

## 대상 데이터
* 0으로 채우기

천 명 당 의료기관병상수  
총 병상 수  
보건복지시설 수(사회복지시설 수)  

체육시설수

## 기후 데이터
평균기온  
평균최고기온  
최고기온  
평균최저기온  
최저기온  
평균 풍속  
최대 순간 풍속  
최대 순간 풍속 풍향  
강수량합

In [77]:
import pandas as pd

num_beds_1000 = pd.read_csv('../data/health(보건)/천명당의료기관병상수.csv')
num_beds = pd.read_csv('../data/health(보건)/총병상수.csv')

## 보건복지 시설 수
#num_welfare = pd.read_csv()

In [78]:
num_beds_1000.head()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
0,강원특별자치도 강릉시,12.5,12.4,11.8,11.3
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
2,강원특별자치도 동해시,15.9,14.5,14.6,14.3
3,강원특별자치도 삼척시,6.2,6.5,6.5,6.7
4,강원특별자치도 속초시,10.5,10.3,10.2,10.1

In [79]:
#sang_hos.loc[sang_hos['SGG_NAME'] == '부산광역시 부산진구',:]
print(num_beds_1000.isna().sum())
print(num_beds.isna().sum())

SGG_NAME           0
BED_PER_1000_20    2
BED_PER_1000_21    2
BED_PER_1000_22    2
BED_PER_1000_23    3
dtype: int64
SGG_NAME        0
BED_TOTAL_20    2
BED_TOTAL_21    2
BED_TOTAL_22    2
BED_TOTAL_23    2
dtype: int64

In [80]:
num_beds_1000[num_beds_1000['BED_PER_1000_23'].isnull()]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
6,강원특별자치도 양양군,NaN,NaN,NaN,NaN
63,대구광역시 군위군,0.4,0.4,0.4,NaN

In [81]:
num_beds[num_beds['SGG_NAME'] == '대구광역시 군위군']

     SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
63  대구광역시 군위군          10.0          10.0          10.0          10.0

* 대구광역시 군위군의 BED_PER_1000_23 컬럼 값은 22년도의 0.4로 동일하게 채웁니다.

In [82]:

num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']['BED_PER_1000_22']

63    0.4
Name: BED_PER_1000_22, dtype: float64

In [83]:
num_beds_1000.loc[num_beds_1000['SGG_NAME'] == '대구광역시 군위군', 'BED_PER_1000_23'] =  num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']['BED_PER_1000_22']

In [84]:
num_beds_1000[num_beds_1000['SGG_NAME'] == '대구광역시 군위군']

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
63,대구광역시 군위군,0.4,0.4,0.4,0.4

In [85]:
## 나머지 값은 0으로 채웁니다.
num_beds_1000[num_beds_1000['BED_PER_1000_20'].isnull()]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,NaN,NaN,NaN,NaN
6,강원특별자치도 양양군,NaN,NaN,NaN,NaN

In [86]:
num_beds_1000.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    2
BED_PER_1000_21    2
BED_PER_1000_22    2
BED_PER_1000_23    2
dtype: int64

In [87]:

#num_beds_1000[num_beds_1000['BED_PER_1000_20'].isnull()]
num_beds_1000_zero = num_beds_1000.fillna(0)

In [88]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [90]:
num_beds_1000_zero.iloc[[1,6],:]

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
1,강원특별자치도 고성군,0.0,0.0,0.0,0.0
6,강원특별자치도 양양군,0.0,0.0,0.0,0.0

In [91]:
num_beds_1000_zero.head()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
0,강원특별자치도 강릉시,12.5,12.4,11.8,11.3
1,강원특별자치도 고성군,0.0,0.0,0.0,0.0
2,강원특별자치도 동해시,15.9,14.5,14.6,14.3
3,강원특별자치도 삼척시,6.2,6.5,6.5,6.7
4,강원특별자치도 속초시,10.5,10.3,10.2,10.1

In [92]:
num_beds_1000_zero.tail()

,SGG_NAME,BED_PER_1000_20,BED_PER_1000_21,BED_PER_1000_22,BED_PER_1000_23
158,충청북도 제천시,17.8,16.8,16.0,15.5
159,충청북도 증평군,6.6,6.7,6.6,5.1
160,충청북도 진천군,10.9,10.1,10.3,10.4
161,충청북도 청주시,12.6,12.6,12.4,12.1
162,충청북도 충주시,12.5,13.4,13.6,13.9

In [93]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [94]:
## num_beds
num_beds.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    2
BED_TOTAL_21    2
BED_TOTAL_22    2
BED_TOTAL_23    2
dtype: int64

In [95]:
num_beds[num_beds['BED_TOTAL_20'].isnull()]

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
1  강원특별자치도 고성군           NaN           NaN           NaN           NaN
6  강원특별자치도 양양군           NaN           NaN           NaN           NaN

In [96]:
num_beds_zero = num_beds.fillna(0, axis=0)

In [97]:
num_beds_zero.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64

In [98]:
num_beds_zero.head()

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
0  강원특별자치도 강릉시        2660.0        2648.0        2499.0        2376.0
1  강원특별자치도 고성군           0.0           0.0           0.0           0.0
2  강원특별자치도 동해시        1439.0        1305.0        1308.0        1268.0
3  강원특별자치도 삼척시         406.0         412.0         412.0         420.0
4  강원특별자치도 속초시         872.0         853.0         848.0         827.0

In [99]:
num_beds_zero.tail()

     SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
158  충청북도 제천시        2364.0        2217.0        2097.0        2020.0
159  충청북도 증평군         244.0         244.0         245.0         192.0
160  충청북도 진천군         911.0         861.0         887.0         898.0
161  충청북도 청주시       10617.0       10699.0       10516.0       10352.0
162  충청북도 충주시        2630.0        2803.0        2825.0        2886.0

In [100]:
num_beds_1000.dtypes

SGG_NAME            object
BED_PER_1000_20    float64
BED_PER_1000_21    float64
BED_PER_1000_22    float64
BED_PER_1000_23    float64
dtype: object

In [102]:
num_beds_1000_zero.isnull().sum()

SGG_NAME           0
BED_PER_1000_20    0
BED_PER_1000_21    0
BED_PER_1000_22    0
BED_PER_1000_23    0
dtype: int64

In [103]:
num_beds_zero.dtypes

SGG_NAME         object
BED_TOTAL_20    float64
BED_TOTAL_21    float64
BED_TOTAL_22    float64
BED_TOTAL_23    float64
dtype: object

In [104]:
num_beds_zero = num_beds_zero.astype(dtype='int64', errors='ignore')

In [105]:
num_beds_zero.dtypes

SGG_NAME        object
BED_TOTAL_20     int64
BED_TOTAL_21     int64
BED_TOTAL_22     int64
BED_TOTAL_23     int64
dtype: object

In [108]:
num_beds_zero.isnull().sum()

SGG_NAME        0
BED_TOTAL_20    0
BED_TOTAL_21    0
BED_TOTAL_22    0
BED_TOTAL_23    0
dtype: int64

In [106]:
num_beds_zero.head()

      SGG_NAME  BED_TOTAL_20  BED_TOTAL_21  BED_TOTAL_22  BED_TOTAL_23
0  강원특별자치도 강릉시          2660          2648          2499          2376
1  강원특별자치도 고성군             0             0             0             0
2  강원특별자치도 동해시          1439          1305          1308          1268
3  강원특별자치도 삼척시           406           412           412           420
4  강원특별자치도 속초시           872           853           848           827

In [107]:
num_beds_zero.to_csv('../processed/총병상수.csv', index=False)
num_beds_1000_zero.to_csv('../processed/천명당의료기관병상수.csv', index=False)